package com.dpxt.domin;

import java.util.HashSet;
import java.util.Set;

/**
 * Huiyuan generated by MyEclipse Persistence Tools
 */

public class Huiyuan implements java.io.Serializable {

	// Fields

	private Long hyid;

	private String hyname;

	private String jine;

	private String password;

	private Set zwyds = new HashSet(0);

	// Constructors

	/** default constructor */
	public Huiyuan() {
	}

	/** minimal constructor */
	public Huiyuan(Long hyid) {
		this.hyid = hyid;
	}

	/** full constructor */
	public Huiyuan(Long hyid, String hyname, String jine, String password,
			Set zwyds) {
		this.hyid = hyid;
		this.hyname = hyname;
		this.jine = jine;
		this.password = password;
		this.zwyds = zwyds;
	}

	// Property accessors

	public Long getHyid() {
		return this.hyid;
	}

	public void setHyid(Long hyid) {
		this.hyid = hyid;
	}

	public String getHyname() {
		return this.hyname;
	}

	public void setHyname(String hyname) {
		this.hyname = hyname;
	}

	public String getJine() {
		return this.jine;
	}

	public void setJine(String jine) {
		this.jine = jine;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getZwyds() {
		return this.zwyds;
	}

	public void setZwyds(Set zwyds) {
		this.zwyds = zwyds;
	}

}