package com.dpxt.domin;

import java.util.HashSet;
import java.util.Set;

/**
 * Yingting generated by MyEclipse Persistence Tools
 */

public class Yingting implements java.io.Serializable {

	// Fields

	private Long ytid;

	private String ytname;

	private Long hang;

	private Long lie;

	private Set fangyings = new HashSet(0);

	// Constructors

	/** default constructor */
	public Yingting() {
	}

	/** minimal constructor */
	public Yingting(Long ytid) {
		this.ytid = ytid;
	}

	/** full constructor */
	public Yingting(Long ytid, String ytname, Long hang, Long lie, Set fangyings) {
		this.ytid = ytid;
		this.ytname = ytname;
		this.hang = hang;
		this.lie = lie;
		this.fangyings = fangyings;
	}

	// Property accessors

	public Long getYtid() {
		return this.ytid;
	}

	public void setYtid(Long ytid) {
		this.ytid = ytid;
	}

	public String getYtname() {
		return this.ytname;
	}

	public void setYtname(String ytname) {
		this.ytname = ytname;
	}

	public Long getHang() {
		return this.hang;
	}

	public void setHang(Long hang) {
		this.hang = hang;
	}

	public Long getLie() {
		return this.lie;
	}

	public void setLie(Long lie) {
		this.lie = lie;
	}

	public Set getFangyings() {
		return this.fangyings;
	}

	public void setFangyings(Set fangyings) {
		this.fangyings = fangyings;
	}

}