/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dpxt.struts.form;

import java.util.ArrayList;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.dpxt.domin.FYDomin;
import com.dpxt.domin.Fangying;
import com.dpxt.domin.KongZhi;
import com.dpxt.domin.ZWDomin;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="temForm"
 */
public class TemForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	String num2 = "2";
	String zwid = "";
	String password = "";
	String kahao = "";
	String mima = "";
	String hyka = "";
	String ytid = "";
	String fyid = "";
	String time ="";
	String date = "";
	String ytName = "";
	String ztsize = "";
	String zongsize= "";
	String id = "";
	String pradio = "1";
	String ypName = "";
	String num = "";
	ArrayList<Fangying> cond = new ArrayList<Fangying>();	
	ArrayList<FYDomin> fy = new ArrayList<FYDomin>();
	ArrayList<ZWDomin> zw = new ArrayList<ZWDomin>();
	ArrayList<KongZhi> kz = new ArrayList<KongZhi>();
	public ArrayList<Fangying> getCond() {
		return cond;
	}
	public void setCond(ArrayList<Fangying> cond) {
		this.cond = cond;
	}
	public ArrayList<FYDomin> getFy() {
		return fy;
	}
	public void setFy(ArrayList<FYDomin> fy) {
		this.fy = fy;
	}
	public ArrayList<KongZhi> getKz() {
		return kz;
	}
	public void setKz(ArrayList<KongZhi> kz) {
		this.kz = kz;
	}
	public String getNum() {
		return num;
	}
	public void setNum(String num) {
		this.num = num;
	}
	public ArrayList<ZWDomin> getZw() {
		return zw;
	}
	public void setZw(ArrayList<ZWDomin> zw) {
		this.zw = zw;
	}
	public String getYpName() {
		return ypName;
	}
	public void setYpName(String ypName) {
		this.ypName = ypName;
	}
	public String getPradio() {
		return pradio;
	}
	public void setPradio(String pradio) {
		this.pradio = pradio;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getZongsize() {
		return zongsize;
	}
	public void setZongsize(String zongsize) {
		this.zongsize = zongsize;
	}
	public String getZtsize() {
		return ztsize;
	}
	public void setZtsize(String ztsize) {
		this.ztsize = ztsize;
	}
	public String getYtName() {
		return ytName;
	}
	public void setYtName(String ytName) {
		this.ytName = ytName;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getTime() {
		return time;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getFyid() {
		return fyid;
	}
	public void setFyid(String fyid) {
		this.fyid = fyid;
	}
	public String getYtid() {
		return ytid;
	}
	public void setYtid(String ytid) {
		this.ytid = ytid;
	}
	public String getHyka() {
		return hyka;
	}
	public void setHyka(String hyka) {
		this.hyka = hyka;
	}
	public String getMima() {
		return mima;
	}
	public void setMima(String mima) {
		this.mima = mima;
	}
	public String getKahao() {
		return kahao;
	}
	public void setKahao(String kahao) {
		this.kahao = kahao;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getZwid() {
		return zwid;
	}
	public void setZwid(String zwid) {
		this.zwid = zwid;
	}
	public String getNum2() {
		return num2;
	}
	public void setNum2(String num2) {
		this.num2 = num2;
	}
	
	
}