/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dpxt.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dpxt.domin.FYDomin;
import com.dpxt.domin.Fangying;
import com.dpxt.domin.Huiyuan;
import com.dpxt.domin.Piao;
import com.dpxt.domin.ZWDomin;
import com.dpxt.domin.Zwyd;
import com.dpxt.service.FYShow;
import com.dpxt.service.FangYingService;
import com.dpxt.service.HYService;
import com.dpxt.service.Pservice;
import com.dpxt.service.YingPianService;
import com.dpxt.service.YingTingService;
import com.dpxt.service.ZwydService;
import com.dpxt.struts.form.TemForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/tem" name="temForm" input="/form/tem.jsp" parameter="qw" scope="request" validate="true"
 */
public class TemAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private HYService hys;
	private YingPianService yps;
	private FangYingService fangYingService;
	private FYShow fys;
	private YingTingService yts;
	private ZwydService zwyds;
	private Pservice pser;
	
	public ZwydService getZwyds() {
		return zwyds;
	}

	public void setZwyds(ZwydService zwyds) {
		this.zwyds = zwyds;
	}

	public FangYingService getFangYingService() {
		return fangYingService;
	}

	public YingPianService getYps() {
		return yps;
	}
	public void setYps(YingPianService yps) {
		this.yps = yps;
	}
	public void setFangYingService(FangYingService fangYingService) {
		System.out.println("32312");
		this.fangYingService = fangYingService;
	}
	public FYShow getFys() {
		return fys;
	}

	public void setFys(FYShow fys) {
		this.fys = fys;
	}
	public YingTingService getYts() {
		return yts;
	}

	public void setYts(YingTingService yts) {
		this.yts = yts;
	}
	public Pservice getPser() {
		return pser;
	}

	public void setPser(Pservice pser) {
		this.pser = pser;
	}
	public HYService getHys() {
		return hys;
	}
	public void setHys(HYService hys) {
		this.hys = hys;
	}
	
	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		@SuppressWarnings("unused")
		TemForm temForm = (TemForm) form;// TODO Auto-generated method stub
		ArrayList<Fangying> lst1=new ArrayList<Fangying>();
		ArrayList<FYDomin> lst=new ArrayList<FYDomin>();
		lst1=(ArrayList<Fangying>) fangYingService.findAll();
		
	
		for(int i=0;i<lst1.size();i++){
			
			FYDomin fyd = new FYDomin();
			fyd.setYpid(lst1.get(i).getYingpian().getYpid()+"");
			fyd.setYtid(lst1.get(i).getYingting().getYtid()+"");
			fyd.setYtName(yts.findById(lst1.get(i).getYingting().getYtid()).getYtname());
			
			
			fyd.setTime((lst1.get(i).getFytime()+"").substring(11, 19));
			fyd.setFyid(lst1.get(i).getFyid()+"");

			if(i-1<0){		
				StringBuffer sb =new StringBuffer();
				List<Fangying> lst4=fangYingService.findByProperty("yingpian", yps.findById((Long)lst1.get(i).getYingpian().getYpid()));
				for(int j=0;j<lst4.size();j++){
					if(lst1.get(j).getFydate().equals(lst1.get(i).getFydate())){
						sb.append(j);
					}
				}
				
				fyd.setNum("1");
				fyd.setCon(lst4.size()+"");
				fyd.setCon2(sb.length()+"");
				fyd.setNum1("1");				
 				fyd.setDate((lst1.get(i).getFydate()+"").substring(0, 10));
				fyd.setYpName(yps.findById((Long)lst1.get(i).getYingpian().getYpid()).getYpname());
				
			}else{
				if(yps.findById((Long)lst1.get(i).getYingpian().getYpid()).getYpname().equals(yps.findById((Long)lst1.get(i-1).getYingpian().getYpid()).getYpname())){
					
					if((lst1.get(i).getFydate()+"").substring(0, 10).equals((lst1.get(i-1).getFydate()+"").substring(0, 10))){
						fyd.setDate((lst1.get(i).getFydate()+"").substring(0, 10));
					}else{				
											
						fyd.setNum1("1");
						
						fyd.setDate((lst1.get(i).getFydate()+"").substring(0, 10));
					}
					fyd.setYpName(yps.findById((Long)lst1.get(i).getYingpian().getYpid()).getYpname());
					if((lst1.get(i).getFydate()+"").substring(0, 10).equals((lst1.get(i-1).getFydate()+"").substring(0, 10))){
						
					}else{
						StringBuffer sb =new StringBuffer();
						List<Fangying> lst4=fangYingService.findByProperty("yingpian", yps.findById((Long)lst1.get(i).getYingpian().getYpid()));
						for(int j=0;j<lst4.size();j++){
							if(lst1.get(j).getFydate().equals(lst1.get(i).getFydate())){
								sb.append(j);
							}
						}
						fyd.setCon2(sb.length()+"");
					}
				}else{
					if((lst1.get(i).getFydate()+"").substring(0, 10).equals((lst1.get(i-1).getFydate()+"").substring(0, 10))){
						fyd.setNum1("1");
						fyd.setDate((lst1.get(i).getFydate()+"").substring(0, 10));
					}else{				
											
						fyd.setNum1("1");
						
						fyd.setDate((lst1.get(i).getFydate()+"").substring(0, 10));
					}
					List lst3=fangYingService.findByProperty("yingpian", yps.findById((Long)lst1.get(i).getYingpian().getYpid()));
					fyd.setNum("1");
					fyd.setCon(lst3.size()+"");
					
					fyd.setYpName(yps.findById((Long)lst1.get(i).getYingpian().getYpid()).getYpname());
				}
			}
			
			lst.add(fyd);
		}		
	
		temForm.setFy(lst); 	   
	   	request.setAttribute("dPForm", temForm);
		return mapping.findForward("showOK");
	}
	@SuppressWarnings("unchecked")
	public ActionForward zwShow(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TemForm temForm = (TemForm) form;
		ArrayList<ZWDomin> zw=new ArrayList<ZWDomin>();
	
		@SuppressWarnings("unused")
		String date=request.getParameter("date");
		String time=request.getParameter("time");
		String ypName =request.getParameter("ypName");
		String ytid = request.getParameter("ytid");
		String fyid = request.getParameter("fyid");
	
System.out.println(ypName);
		temForm.setYtid(ytid);
		temForm.setFyid(fyid);
		temForm.setDate(date);
		temForm.setTime(time);
		temForm.setYpName(ypName);
		temForm.setYtName(yts.findById(Long.valueOf(ytid)).getYtname());
		Fangying fy=fangYingService.findById(Long.valueOf(fyid));
		StringBuffer size =new 	StringBuffer();
		List<Zwyd> lst= zwyds.findByProperty("fangying", fy);

		for(int i=0;i<lst.size();i++){
			StringBuffer size1 = new StringBuffer();
			ZWDomin zwd= new ZWDomin();
			if(i==0){
				
				zwd.setCount("0");
			}
			if(i<(lst.size()-2)){
				if(lst.get(i+1).getHang().equals(lst.get(i).getHang())){
					//System.out.println("sadsa");
					
				}else{
					//zwd.setCount("0");
					zwd.setNum("1");
					
				}
			}
			zwd.setId(i+"");
			zwd.setZht(lst.get(i).getZt()+"");	
			
			if(lst.get(i).getZt()==1){
				size1.append(lst.get(i).getZt());
				size.append(size1);
			}
			zwd.setHang(lst.get(i).getHang()+"");
			zwd.setLie(lst.get(i).getLie()+"");
			zw.add(zwd);
			
		}
		temForm.setZtsize(size.length()+"");
		temForm.setZongsize(lst.size()+"");
		
		temForm.setZw(zw);
		
//request.setAttribute("dPForm", dpForm);
		return mapping.findForward("xuanzuoOK");
	}
	public ActionForward qrShow(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TemForm temForm = (TemForm) form;
		
		ArrayList<FYDomin> fy1=new ArrayList<FYDomin>();
		String str =temForm.getId();
		String[] str2=str.split(",");
		String radio=temForm.getPradio();
		String str1 = temForm.getZwid();
		String[] str3= str1.split(",");
		int j =Integer.parseInt(radio);
//System.out.println("12-23".substring(0,2));
	
		
		for(int i=0;i<str2.length;i++){
			FYDomin fy= new FYDomin();
			fy.setZwid(str3[i]);
			fy.setDate(temForm.getDate());
			fy.setTime(temForm.getTime());
			fy.setMoney(pser.findById(Long.valueOf(j-1)).getPrice());
			fy.setYpName(temForm.getYpName());
			fy.setYtName(temForm.getYtName());
			fy.setYthao(str2[i]);
			fy1.add(fy);
		}
		
		temForm.setFy(fy1);
		
		request.getSession().setAttribute("temForm", temForm);
		return mapping.findForward("qr");
	}

	@SuppressWarnings("unchecked")
	public ActionForward ydShow(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {	
		@SuppressWarnings("unused")
		TemForm temForm = (TemForm) form;
		@SuppressWarnings("unused")
		ArrayList<Zwyd> lst3 = new ArrayList<Zwyd>(); 
		TemForm tem = (TemForm) request.getSession().getAttribute("temForm");
		ArrayList<FYDomin> lst1= tem.getFy();
		
		String kahao = temForm.getKahao();
		String password = temForm.getPassword();
		String message = "";
		String jing ="";
		List<Huiyuan> lst;		
		lst = hys.findByProperty("hyname", kahao);
System.out.println(tem.getFyid());	
		
		if(lst.size()==0){
			tem.setNum2("0");
			request.setAttribute("temForm", tem);
			message="qr";
		}else if(password.equals(lst.get(0).getPassword())){			
			jing = lst.get(0).getJine();
			if(Integer.parseInt(jing)<(lst1.size()*Integer.parseInt(lst1.get(0).getMoney()))){
				tem.setNum2("1");
				request.setAttribute("temForm", tem);
				message="qr";
			}else{
				for(int i=0;i<lst1.size();i++){
					String ythao = lst1.get(i).getYthao();				
					List<Zwyd> zwyd1 = zwyds.findByProperty("fangying", fangYingService.findById(Long.valueOf(tem.getFyid())));
				System.out.println(ythao.substring(0, ythao.indexOf("-")));
				System.out.println(ythao.substring(ythao.indexOf("-")+2,ythao.length()-1));
					for(int j=0;j < zwyd1.size();j++){
						if(ythao.substring(0, ythao.indexOf("-")).equals(String.valueOf(zwyd1.get(j).getHang()))&&ythao.substring(ythao.indexOf("-")+2,ythao.length()-1).equals(String.valueOf(zwyd1.get(j).getLie()))){
							Zwyd zwyd = zwyd1.get(j);
							zwyd.setHuiyuan((Huiyuan)hys.findByProperty("hyname", kahao).get(0));
							zwyd.setPiao((Piao)pser.findByProperty("price", lst1.get(0).getMoney()).get(0));
							zwyd.setFangying(fangYingService.findById(Long.valueOf(tem.getFyid())));						
							zwyd.setZwzht("Î´Ñ¡ÖÐ");
							zwyd.setZt(Long.valueOf(1));						
							zwyds.attachDirty(zwyd);
						}					
					}
				}
				int i=Integer.parseInt(jing)-lst1.size()*Integer.parseInt(lst1.get(0).getMoney());
				Huiyuan hy=lst.get(0);
				
				hy.setJine(String.valueOf(i));
				hys.attachDirty(hy);
				List<Zwyd> lst5 =  zwyds.findByProperty("huiyuan", hys.findByProperty("hyname", kahao).get(0));
				ArrayList<FYDomin> lst4 = new ArrayList<FYDomin>();
				for(int j=0;j < lst5.size();j++){
					FYDomin fyd =new FYDomin();
					//fyd.setDate()
				}
				temForm.setFy(lst4);
				message="yd";
			}			
			
		}else{
			tem.setNum2("0");
			request.setAttribute("temForm", tem);
			message="qr";
		}
		return mapping.findForward(message);
	}
	public ActionForward yulan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TemForm temForm = (TemForm) form;
		return mapping.findForward("yulan");
	}
	public ActionForward quxiao(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		@SuppressWarnings("unused")
		TemForm temForm = (TemForm) form;
		return mapping.findForward("quxiao");
	}
}